"""updated bus model

Revision ID: 13ad99ec2c13
Revises: 9b950ac55209
Create Date: 2025-02-28 09:18:16.316065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ad99ec2c13'
down_revision = '9b950ac55209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ticket_price', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'route', ['route_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ticket_price')
        batch_op.drop_column('route_id')

    # ### end Alembic commands ###
