"""Add driver_id to routes

Revision ID: 5324a76ef6df
Revises: f83cb8c7843e
Create Date: 2025-03-01 02:51:32.255128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5324a76ef6df'
down_revision = 'f83cb8c7843e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['driver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('driver_id')

    # ### end Alembic commands ###
