"""Updated bus and route relationship

Revision ID: f1a0f8e5f92c
Revises: 5324a76ef6df
Create Date: 2025-03-04 01:39:08.080308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a0f8e5f92c'
down_revision = '5324a76ef6df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'route', ['route_id'], ['id'])

    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_constraint('route_bus_id_fkey', type_='foreignkey')
        batch_op.drop_column('bus_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bus_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('route_bus_id_fkey', 'bus', ['bus_id'], ['id'])

    with op.batch_alter_table('bus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('route_id')

    # ### end Alembic commands ###
