"""updated bus and route model

Revision ID: f83cb8c7843e
Revises: 13ad99ec2c13
Create Date: 2025-02-28 23:43:27.982705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f83cb8c7843e'
down_revision = '13ad99ec2c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus', schema=None) as batch_op:
        batch_op.drop_constraint('bus_route_id_fkey', type_='foreignkey')
        batch_op.drop_column('route_id')

    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.alter_column('departure_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('departure_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('bus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('bus_route_id_fkey', 'route', ['route_id'], ['id'])

    # ### end Alembic commands ###
